Develop
kaidou2/homework7 pull request #1
Opened 2022-10-22 13:29 UTC by kaidou2

レビューお願いします

2022-10-23 12:50 UTC, YudaiNoda3576 requested changes
コメントしています！

また、今回のPRに含まれていないファイルもいくつか気になったので一緒に対応のほどお願いします🙏
* CreateFormとUpdateFormの違いは何でしょうか？
* .classファイルや.binファイルはGitHubで管理すべきファイルでしょうか？

2022-10-23 12:50 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createName(@RequestBody @RequestParam(value = "text") String text, @Validated @Length(min=8, max=20 ) CreateForm form) {
Validationが正しく動作しているかどうか検証するために、7文字のパターン、8文字のパターン、9
文字のパターン、19文字のパターン、20文字のパターン、21文字のパターンのスクショが欲しいです！（こういう検証の仕方を境界値テストと言います）

2022-10-23 12:50 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
>      URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
ここですが`http://localhost:8080`がハードコードされているので、動的に値を取得できるように修正のほどお願いします🙏

2022-10-23 12:50 UTC, YudaiNoda3576 commented on homework7/src/main/resources/application.properties
> +
この修正は必要な修正でしょうか？

2022-10-23 12:50 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createName(@RequestBody @RequestParam(value = "text") String text, @Validated @Length(min=8, max=20 ) CreateForm form) {
また、これだと`name`属性単体に対してValidationがかかっていないように見えるのですが、そのようになってますか？
せっかくFormクラスを作成頂いているのでそちらにValidationを設定した方がいいかもですね！
また、Validationにかかった場合の処理が不足しているのでそちらも対応のほどお願いします！

2022-10-30 12:07 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createName(@RequestBody @RequestParam(value = "text") String text, @Validated @Length(min=8, max=20 ) CreateForm form) {
- Validationが正しく動作しているかどうか検証するために、7文字のパターン、8文字のパターン、9
文字のパターン、19文字のパターン、20文字のパターン、21文字のパターンのスクショが欲しいです！
>それぞれのパターンのスクショをREADMEのところに貼り付けておきました。

- name属性単体に対してValidationがかかっていないように見える
>Formクラスにバリデーションを設定しました。

2022-10-30 12:10 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
>      URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
- http://localhost:8080がハードコードされているので、動的に値を取得できるように修正のほどお願いします🙏
>@PathVariableで動的に値を取得できるようにしました。

2022-10-30 12:11 UTC, kaidou2 commented on homework7/src/main/resources/application.properties
> +
空行を削除しました。

2022-11-06 13:52 UTC, merged