Update RestController.java
kaidou2/homework7 pull request #2
Opened 2022-11-07 01:14 UTC by kaidou2

URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")　　の
　　.path("/names/id")　　を

　　.queryParam("names", "name")　　に変更しました。

2022-11-10 03:13 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-11-10 03:13 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
>      URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
この部分なんですが、ハードコードされているので、動的に取得できるように修正してみてください！
ハードコードが何かわからなければ検索してみてください〜
また、よくありがちな修正で変数に格納すると言う対応をいただくことがあるのですが、特定のクラスを使用することでそもそもコード上に`http://localhost:8080` を記載する必要がなくなるのでそちらの方法を検索してみてください！

どうしても分からない場合は過去の受講生さんのリポジトリを参考にしてみるなども検討してみてください！

2022-11-14 06:45 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
>      URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
POSTメソッドとPATCHメソッドのハードコードされている所を、修正しました。POSTメソッドの引数にUriComponentsBuilder builderを追加して、String path = "/names/" + form.getName();で動的にパラメータを取得できるようにしました。PATCHメソッドも同様です。

2022-11-14 09:34 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
>      URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
POSTとPATCHは、8文字以上20字以下の文字列だと受け取り、それ以外は受け取らないようになってます。以下、POSTとPATCHで7,8,9,19,20,21字でテストした結果です。PATCHのURLはnames/と?の間に整数(IDという設定)を入れるという仕組みにしてます。
![スクリーンショット (102)](https://user-images.githubusercontent.com/111167638/201623881-253068e6-20af-48bf-8b2f-c7d3a9f7c815.png)
![スクリーンショット (103)](https://user-images.githubusercontent.com/111167638/201623888-0f6fbd0c-6c04-4235-bb5d-aa906f90f7bc.png)
![スクリーンショット (104)](https://user-images.githubusercontent.com/111167638/201623890-9a7d5237-12b7-4d23-aefe-d3c72d230b1c.png)
![スクリーンショット (105)](https://user-images.githubusercontent.com/111167638/201623893-a049fd64-f39e-4b57-bd78-87ce64cb7192.png)
![スクリーンショット (106)](https://user-images.githubusercontent.com/111167638/201623897-92931402-5149-473f-83a0-f0c68c21a6d0.png)
![スクリーンショット (107)](https://user-images.githubusercontent.com/111167638/201623899-13bc385f-7b4b-4b78-8d93-43a429ce02f6.png)
![スクリーンショット (108)](https://user-images.githubusercontent.com/111167638/201623903-a3bff03a-5f96-453b-8874-9bfaebfa38d3.png)
![スクリーンショット (109)](https://user-images.githubusercontent.com/111167638/201623906-8f2a82ce-8e3d-4b54-8329-28afc8c59040.png)
![スクリーンショット (110)](https://user-images.githubusercontent.com/111167638/201623910-1cacefa3-10d8-4579-bce4-b488233bf20c.png)
![スクリーンショット (111)](https://user-images.githubusercontent.com/111167638/201623914-e3e69cec-2d27-48d3-8852-87f7bfde2f82.png)
![スクリーンショット (112)](https://user-images.githubusercontent.com/111167638/201623918-68674ecf-5ae2-4d38-8906-def6a7354fd0.png)
![スクリーンショット (113)](https://user-images.githubusercontent.com/111167638/201623924-bed816ac-39d4-43ef-8b94-c08ab6ff91b8.png)

2022-11-15 00:23 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-11-15 00:23 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createUser(@RequestBody @RequestParam(value = "name") String name, @Validated @NotNull UserForm form, UriComponentsBuilder builder) {
@NotNullは必要そうですか？

2022-11-15 00:23 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
このIDってどこで使われてますか？
また、なぜ大文字なんでしょうか？？

2022-11-15 01:20 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createUser(@RequestBody @RequestParam(value = "name") String name, @Validated @NotNull UserForm form, UriComponentsBuilder builder) {
@Lengthがあるので必要なかったですねw
削除しました。後、UserFormクラスにあるsetNameメソッドも使わないので削除しました。

2022-11-15 02:22 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
変数pathに入れるのをうっかり忘れてましたね。入れておきました。

2022-11-15 02:32 UTC, YudaiNoda3576 reviewed
コメントしています〜

2022-11-15 02:32 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/UserForm.java
> +
UserFormのNotNullも不要なんでしょうか？？
nameをNULLにした場合の実行結果ってどうなりますか？

2022-11-15 02:35 UTC, YudaiNoda3576 requested changes
コメントしています〜

2022-11-15 02:35 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
大文字のままなのは何故でしょうか・・・？
また、このIDって何に使われる情報か考えてみてください。
そうなると実装の方法を変える必要があることに気づけるかと思います！

2022-11-15 04:43 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
すいません、大文字のことについて忘れていました。大文字にしてるのは、idは整数型で、文字列型に変えるときに同じ変数名だとエラーになるからです。調べたところ、toStringメソッドを利用する場合「null」チェックを行わないとシステムエラーとなってしまうみたいで、nullでも構わないので、valueOfメソッドに変更しました。

2022-11-15 04:53 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/UserForm.java
> +
8文字以上20字以下で受け付けるという設定で0字はアウトで、@Lengthでそう設定しているので@NotNullはいらないかと思いました。これが0字の結果です。400エラーなので8文字以上20字以下ルールに引っかかってるということなのかと思いましたが、もしかしたら間違ってるかもしれません。
![スクリーンショット (116)](https://user-images.githubusercontent.com/111167638/201829085-c059a417-cbf6-445e-9404-7705f24c997c.png)
![スクリーンショット (114)](https://user-images.githubusercontent.com/111167638/201829099-55ea289a-f85d-481d-a0e2-1348adff4e4b.png)

2022-11-15 05:21 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createUser(@RequestBody @RequestParam(value = "name") String name, @Validated @NotNull UserForm form, UriComponentsBuilder builder) {
アノテーションの付ける場所の問題ですかね！
以前同じ内容を指摘したような気がするのでその時のやりとりをGitHubの履歴から検索するとヒントがわかるかも・・・？

2022-11-15 05:22 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
slackから転載

変数名が大文字のID  となっているのが命名規則に則っていないのでJavaの命名規則に則って修正して欲しいです:祈る:

2022-11-15 10:06 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +  public ResponseEntity<String> createUser(@RequestBody @RequestParam(value = "name") String name, @Validated @NotNull UserForm form, UriComponentsBuilder builder) {
nameが空文字、null、20文字以上だと受け取らないという仕様に変更しました。UserFormクラスのnameのバリデーションに@NotNullを追加して、@Lengthを(min = 1, max = 19)にしました。

2022-11-15 10:08 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String ID = Integer.valueOf(id).toString();
整数型idを文字列型に変更後の変数名をIDからidNumberに変更しました。

2022-11-15 13:54 UTC, YudaiNoda3576 reviewed
コメントしています〜

2022-11-15 13:54 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/UserForm.java
> +  @Length(min = 1, max = 19)
minimumの設定はなぜ必要ですか？
max=19の指定って19文字の時はどうなりましたっけ？

2022-11-15 13:59 UTC, YudaiNoda3576 requested changes
コメントしています！
更新処理ですが、idで特定のUser情報を引っ張ってきて、実際にそのUserの情報を更新するようにしてみましょう！

2022-11-15 13:59 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String idNumber = String.valueOf(id);
シンプルに`id`でも良いような気がします！

2022-11-15 23:41 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/UserForm.java
> +  @Length(min = 1, max = 19)
max = 19だと19文字までは受け付けて、20文字以上だと受け付けないという設定になりますね。
@NotNullだとnullは受け付けないけど空文字は受け付けるという設定になってしまうので、両方ともはじける@NotEmptyに変更しました。

2022-11-15 23:54 UTC, Horikawa-1 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String idNumber = String.valueOf(id);
PATCHメソッドの引数の「int id」を「String id」に変更して、Userformクラスに「private String id」と「public String getId() { return id;}」を追加して、PATCHメソッドのpathにform.getId()でidの値を代入するようにしました。

2022-11-16 02:01 UTC, YudaiNoda3576 reviewed
コメントしています！

2022-11-16 02:01 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String path = "/names/" + form.getId() + form.getName();
formからidは入力されないと思うので、パス変数からidを取得する必要があります！

2022-11-16 03:22 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String path = "/names/" + form.getId() + form.getName();
パス変数からidを取得するというのがよく分からないです。
後、一応通信はできています。
![image](https://user-images.githubusercontent.com/111167638/202075722-2e3421b2-c5e7-4628-95c1-3c3a99364979.png)
![image](https://user-images.githubusercontent.com/111167638/202075797-9de19cd9-c2e9-4d4d-81b8-f3011f4de85b.png)

2022-11-16 07:24 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String path = "/names/" + form.getId() + form.getName();
@kaidou2
> パス変数からidを取得するというのがよく分からない

以前の実装でやっていたことだと思うのですが、どこが分からないか具体的に教えて頂けないですか・・・？
 
```suggestion
   String id = String.valueOf(id);
```

2022-11-16 08:02 UTC, kaidou2 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String path = "/names/" + form.getId() + form.getName();
パス変数というのはpathのことでしょうか？
> formからidは入力されないと思う
PATCHメソッドの引数にidがあって、userFormクラスに「private String id」があるので値が渡っていると思ったのですが、違うのでしょうか？間違ってるとしたらidはnameと違って@PatchMapping("/names/{id}")に{}で囲んでいることや、@RequestParam(value = "name")じゃなくて@PathVariable("id")で指定していることに原因があるのかもしれないとか思ってます。

2022-11-16 14:13 UTC, YudaiNoda3576 commented on homework7/src/main/java/raisetech/homework7/RestController.java
> +    String path = "/names/" + form.getId() + form.getName();
> パス変数というのはpathのことでしょうか？

違いますね！
調べてみてください〜

2022-12-17 14:37 UTC, merged